language: objective-c
compiler:
  - clang
git:
  submodules: false
before_install:
  - sed -i '' 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
before_script:
  - git clone git://github.com/takram-design-engineering/takram-math.git ../takram-math
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
  - make test
notifications:
  slack:
    secure: bzlnmEb9x7k6nX04fctkj2wKHfUHnUBB3Vc/uqMBkGoYy5GLkUa3v8V5Lg11vp5gDpV6I04l+EQVl45fOqCSjKpmKO+y946xjCx3pmvDCv/NpA+diioAR+lrLxyCqEogmyNaW4ii6NUJyMyemImjYcy/VMwye3/+jmJSQq5rECWplzVshKgwfIFd0D0fSvH5HvTiwi/Yo0PgYgPQFXetfs+mU63a/pnKxJlvd0SeKV5h9PB+XoEugVMmtEcSWv8gZfxFjEsLIxFs1qcbmN6PobfmBj7pqOs7YUSmVvhvMR00qu6awGX8owiwdYjBJVlNr/V6K56Io2rfyEAQf3X7qnFf0nghpBBGsloirnajDsHt+jVvfU1sczDSJ5tBPF9shX+L+hiR1f7eMgw9+kyBqN6EnZYwkK9RGBLQemUugtQ0lsaHLzSaPFH8PWnvshtjYu6nyFaRWX6fDePNdVhh2lVJGt+U4Wp2+CHUAjKD5hSuGRGYC6KXSbGSu3mO9ifd8sVY6F/DJJrtAvSW6/g3e9QJYu+g4WMROKa//Rv6AWuiF5eUP9QSwDrkaGt9eAaaYaUY98kvdwqqRClyTFgFjMWu/e7vnAR9xBHKaKtPoPDLvq79gNOv4nlHX5yvLWfy2CmBXZof4lmLMhIzJuLfxpsB38Guimg73tipyH8vKY8=
